# application.yml template
spring:
  profiles:
    active: docker
server:
  contextPath: /trypolicy
  port: 8449
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: /java/MHC_LOGS/try-policy/tryPolicy.log
  level:
    gov:
      samhsa:
        mhc.trypolicy: DEBUG
    javax.validation: DEBUG
dss:
  segment:
    dssUrl: https://localhost:8450/dss/segmentedDocument
    ccdUrl: https://localhost:8446/pcm/patients/clinicaldocuments/ccd/
    obligationUrl: https://localhost:8446/pcm/patients/
    defaultIsAudited: false
    defaultIsAuditFailureByPass: true
    pdpDecision: PERMIT
    homeCommunityId: dddd

---
spring.profiles: docker
server.ssl:
  key-store: /java/keystore/mhc.keystore
  key-store-password: changeit
dss:
  segment:
    dssUrl: https://dss.mhc:8450/dss/segmentedDocument
    ccdUrl: https://pcm.mhc:8446/pcm/patients/clinicaldocuments/ccd/
    obligationUrl: https://pcm.mhc:8446/pcm/patients/


