server:
  port: 8449
logging:
  file: /java/MHC_LOGS/try-policy/tryPolicy.log
  level:
    gov:
      samhsa:
        mhc.trypolicy: DEBUG
    javax.validation: DEBUG
info:
  component: TRY POLICY API
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
dss:
  segment:
    defaultIsAudited: false
    defaultIsAuditFailureByPass: true
    pdpDecision: PERMIT
    homeCommunityId: dddd
---
spring.profiles: ssl
server:
  port: 8449
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /trypolicy
---
spring.profiles: docker
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true
