# application.yml template
dss:
  serviceEndPointUrl: http://bhitsdemoapp01/DocumentSegmentation-bl/services/DSS
logging:
  file: C:/java/PP_PROPS/tryPolicy.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      herasaf: ERROR
    gov:
      samhsa:
        tryPolicy: DEBUG
# application.yml
polrep:
  c2sPolrepScheme: http
  c2sPolrepHost: localhost
  c2sPolrepPort: 8080
  c2sPolrepContext: polrep-web
  c2sPolrepVersion: latest
  pidDomainId: 2.16.840.1.113883.3.72.5.9.4
  pidDomainType: ISO
  empiEndPtUrl: http\://BHITSDEVACS01/openempi-admin/services/PIXManager_Port_Soap12
spring:
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/polrep?autoReconnect=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: select 1
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 1800000
    numTestsPerEvictionRun: 3
    minEvictableIdleTimeMillis: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: validate
          #auto: create
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
# polrep:
  # policySet:
    # combiningAlgs:
      # first-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:first-applicable
      # ordered-deny-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-deny-overrides
      # ordered-permit-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-permit-overrides
      # deny-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:deny-overrides
      # only-one-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:only-one-applicable
      # permit-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:permit-overrides
pcm:
  ccd:
    url: http://localhost:8083/pcm/patients/clinicaldocuments/ccd/
  xacml:
    url: http://localhost:8083/pcm/xacml/