# application.yml template

logging:
  file: C:/java/PP_PROPS/tryPolicy.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      herasaf: ERROR
    gov:
      samhsa:
        tryPolicy: DEBUG
polrep:
  c2sPolrepScheme: http
  c2sPolrepHost: localhost
  c2sPolrepPort: 8080
  c2sPolrepContext: polrep-web
  c2sPolrepVersion: latest
  pidDomainId: 2.16.840.1.113883.3.72.5.9.4
  pidDomainType: ISO
  empiEndPtUrl: http\://BHITSDEVACS01/openempi-admin/services/PIXManager_Port_Soap12
dss:
  serviceEndPointUrl: http://bhitsdemoapp01/DocumentSegmentation-bl/services/DSS



